 - apiVersion: v1
  kind: Namespace
  metadata:
    name: default-1687789798031
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: saasden-mehmood
    namespace: default-1687789798031
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: saasden-mehmood
    template:
      metadata:
        labels:
          app: saasden-mehmood
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: saasden-mehmood
            image: saasdencontainer.azurecr.io/saasden-mehmood:latest
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G
- apiVersion: v1
  kind: Service
  metadata:
    name: saasden-mehmood-service
    namespace: default-1687789798031
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
    selector:
      app: saasden-mehmood
