apiVersion: v1
kind: Namespace
metadata:
  name: saasden-deployment
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saasden-mehmood
  namespace: saasden-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saasden-mehmood
  template:
    metadata:
      labels:
        app: saasden-mehmood
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: saasden-mehmood
          image: saasdencontainer.azurecr.io/saasden-mehmood:latest
          ports:
            - containerPort: 9020
          resources:
            requests:
              cpu: "0"
              memory: "0"
            limits:
              cpu: "256"
              memory: 11400G
---
apiVersion: v1
kind: Service
metadata:
  name: saasden-mehmood-service
  namespace: saasden-deployment
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9020
      name: port9020
      port: 9020
      protocol: TCP
  selector:
    app: saasden-mehmood
